# Start AeroSpace at login
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true
accordion-padding = 300

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[key-mapping]
preset = 'qwerty'

[mode.main.binding]
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-v = ['workspace V', 'exec-and-forget /usr/bin/open -a "/Applications/Firefox.app"']
alt-c = ['workspace C', 'exec-and-forget /usr/bin/open -a "/Applications/Slack.app"']
alt-m = 'exec-and-forget /usr/bin/osascript -e "tell application \"System Events\" to set visible of (first process whose frontmost is true) to false"'
alt-a = ['workspace A', 'exec-and-forget /usr/bin/open -a "/Applications/Google Chrome.app"']
alt-f = 'fullscreen'
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-ctrl-f = 'layout floating tiling'
alt-tab = 'workspace-back-and-forth'

[workspace-to-monitor-force-assignment]
A = 'Built-in Retina Display'

[[on-window-detected]]
if.workspace = 'V'
if.app-name-regex-substring = 'firefox'
run = 'layout tiling'

[[on-window-detected]]
if.workspace = 'C'
if.app-name-regex-substring = 'Slack'
run = 'layout tiling'

[[on-window-detected]]
if.workspace = 'A'
if.app-name-regex-substring = 'Google Chrome'
run = 'layout tiling'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']